### PR TITLE
Use an unordered_set in thin_with_voxel

### PR DESCRIPTION
**Pull request by Jean-Romain**
@tiagodc could you benchmark that on TLS data.

### CODE REVIEW

**Comment by tiagodc** [comment]
sure

**Comment by tiagodc** [comment]
## `-thin_with_voxel` TLS benchmark
- CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
- cores: 8 (4 physical x 4 threads)
- RAM: 16 Gb
- average CPU usage during file streaming: 10%
- reading function: `lidR::readLAS` 

### Cloud 1
- N: 2,541,917 points
- extents: 30 x 30 x 14 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (Gb) |
| --- | --- | --- | --- |
| 0.1 | 349,787 | 4 | 0.06 |
| 0.05 | 925,881 | 5 | 0.12 |
| 0.025 | 1,718,986 | 7 | 0.18 |
| 0.01 | 2,414,604 | 7 | 0.25 |

### Cloud 2
- N: 10,773,659 points
- extents: 86 x 127 x 19 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (Gb) |
| --- | --- | --- | --- |
| 0.1 | 1,049,797 | 16 | 0.11 |
| 0.05 | 2,907,514 | 18 | 0.23 |
| 0.025 | 6,252,097 | 28 | 0.51 |
| 0.01 | 9,947,220 | 32 | 0.99 |

### Cloud 3
- N: 42,869,489 points
- extents: 400 x 217 x 56 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (Gb) |
| --- | --- | --- | --- |
| 0.1 | 2,606,613 | 91 | 0.21 |
| 0.05 | 7,602,382 | 104 | 0.67 |
| 0.025 | 19,556,071 | 126 | 1.62 |
| 0.01 | 37,853,465 | 138 | 3.18 |

### Cloud 4
- N: 165,155,435 points
- extents: 259 x 234 x 193 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (Gb) |
| --- | --- | --- | --- |
| 0.1 | 1,506,216 | 187 | 0.31 |
| 0.05 | 4,552,934 | 208 | 0.87 |
| 0.025 | 12,987,644 | 231 | 1.14 |
| 0.01 | 41,461,462 | 309 | 3.50 |

**Comment by Jean-Romain** [comment]
Thank you Tiago but what I was expecting was a comparison between `set` and `unordered_set`. On ALS data I benchmarked a gain of ~33%

**Comment by tiagodc** [comment]
oh crap... I didn't see you created a new branch for that. OK, I'll pull the `unordered_set` branch, recompile and perform the tests again... no problem

**Comment by tiagodc** [comment]
## `-thin_with_voxel` TLS benchmark using `unordered_set`
- CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
- cores: 8 (4 physical x 4 threads)
- RAM: 16 GB
- average CPU usage during file streaming: 25% - *last time my PC was under power management*
- reading function: `lidR::readLAS` 

### Cloud 1
- N: 2,541,917 points
- extents: 30 x 30 x 14 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (GB) |
| --- | --- | --- | --- |
| 0.1 | 349,787 | 1 | 0.03 |
| 0.05 | 925,881 | 1 | 0.12 |
| 0.025 | 1,718,986 | 2 | 0.14 |
| 0.01 | 2,414,604 | 2 | 0.23 |

### Cloud 2
- N: 10,773,659 points
- extents: 86 x 127 x 19 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (GB) |
| --- | --- | --- | --- |
| 0.1 | 1,049,797 | 6 | 0.28 |
| 0.05 | 2,907,514 | 7 | 0.38 |
| 0.025 | 6,252,097 | 10 | 0.50 |
| 0.01 | 9,947,220 | 13 | 0.81 |

### Cloud 3
- N: 42,869,489 points
- extents: 400 x 217 x 56 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (GB) |
| --- | --- | --- | --- |
| 0.1 | 2,606,613 | 32 | 0.22 |
| 0.05 | 7,602,382 | 37 | 0.64 |
| 0.025 | 19,556,071 | 50 | 1.68 |
| 0.01 | 37,853,465 | 65 | 3.31 |

### Cloud 4
- N: 165,155,435 points
- extents: 259 x 234 x 193 m

| Voxel spacing (m) | surviving points | read time (s) | ~ memory usage (GB) |
| --- | --- | --- | --- |
| 0.1 | 1,506,216 | 72 | 0.37 |
| 0.05 | 4,552,934 | 77 | 0.82 |
| 0.025 | 12,987,644 | 104 | 0.88 |
| 0.01 | 41,461,462 | 140 | 3.44 |

### Conclusions
- Memory usage hasn't changed
- Speed improved a bit - up to ~10% in some cases, but overall it was the same

**Comment by Jean-Romain** [comment]
Why do you say 10% improvement. Comparing the two tables I see a > 50% improvement.

**Comment by tiagodc** [comment]
The time is proportional to the CPU usage... the first time I ran the tests my PC was in power management mode and only used the CPU at 10%... the second time it was 25% as it was charging, so the speed improvement was 2.5 times due to the CPU, any extra is due the usage of `unordered_set` instead of `set`...

**Comment by Jean-Romain** [comment]
Slightly better in computation time. No worst in memory usage. Ok I merge.

**Pull request merged**
